### ISSUE TITLE
Handle empty asana tasks

### ISSUE THREAD

**Issue by marcboscher** [marcboscher/crosscheck#12]
if type enter in asana task list, creates an empty task

sync throws exception

handle it.

**Comment by desireco** [comment]
Years later, this is still an issue. You guys are hating us or something

**Comment by marcboscher** [comment]
hmmm, this project is deprecated @desireco and has been for some time. Check out https://unito.io/sync/asana/github for its replacement.

**Comment by desireco** [comment]
I realized that :) sorry @marcboscher thanks
